name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ruby セットアップ
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Jekyll build
      - name: Build Jekyll blog
        run: |
          cd blog_src
          bundle install
          bundle exec jekyll build

      # 会社HPとブログをまとめて gh-pages にデプロイ
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./               # main 直下の会社HPと blog_src/_site をまとめてコピー
          keep_files: false
          publish_branch: gh-pages
